-- RUN THIS IN YOUR SUPABASE SQL EDITOR TO FIX REGISTRATION ERRORS

-- 1. Disable Row Level Security (RLS) for the users table
ALTER TABLE IF EXISTS users DISABLE ROW LEVEL SECURITY;

-- 2. Ensure the table has the correct structure
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'student',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Grant all permissions to the anon role (just in case)
GRANT ALL ON TABLE users TO anon;
GRANT ALL ON TABLE users TO authenticated;
GRANT ALL ON TABLE users TO service_role;
